const seedProducts = [
  // Group A: Victoria's Secret (Category: Mists & Body Care)
  { name: "Pure Seduction", brand: "Victoria's Secret", category: "Body Mists & Care", price: 2500, scent_family: "Floral", top_notes: "Plum", heart_notes: "Freesia", base_notes: "Chamomile", vibe_tag: "Flirty", intensity: "Medium", occasion: "Daily", description: "A flirty, floral fragrance.", image_url: "/assets/mist_placeholder.png" },
  { name: "Velvet Petals", brand: "Victoria's Secret", category: "Body Mists & Care", price: 2500, scent_family: "Floral", top_notes: "Lush Blooms", heart_notes: "Almond Glaze", base_notes: "Sandalwood", vibe_tag: "Warm", intensity: "Medium", occasion: "Daily", description: "Lush blooms and almond glaze.", image_url: "/assets/mist_placeholder.png" },
  { name: "Bare Vanilla", brand: "Victoria's Secret", category: "Body Mists & Care", price: 2500, scent_family: "Oriental", top_notes: "Whipped Vanilla", heart_notes: "Soft Cashmere", base_notes: "Apple Blossom", vibe_tag: "Sweet", intensity: "Medium", occasion: "Daily", description: "Whipped vanilla and soft cashmere.", image_url: "/assets/mist_placeholder.png" },
  { name: "Love Spell", brand: "Victoria's Secret", category: "Body Mists & Care", price: 2500, scent_family: "Fruity", top_notes: "Cherry Blossom", heart_notes: "Peach", base_notes: "White Jasmine", vibe_tag: "Playful", intensity: "Medium", occasion: "Daily", description: "Cherry blossom and fresh peach.", image_url: "/assets/mist_placeholder.png" },
  { name: "Amber Romance", brand: "Victoria's Secret", category: "Body Mists & Care", price: 2500, scent_family: "Oriental", top_notes: "Black Cherry", heart_notes: "Crème Anglaise", base_notes: "Sandalwood", vibe_tag: "Warm", intensity: "Medium", occasion: "Evening", description: "Deep amber and sugar kisses.", image_url: "/assets/mist_placeholder.png" },
  { name: "Coconut Passion", brand: "Victoria's Secret", category: "Body Mists & Care", price: 2500, scent_family: "Fruity", top_notes: "Island Coconut", heart_notes: "Warm Sands", base_notes: "Vanilla", vibe_tag: "Tropical", intensity: "Medium", occasion: "Summer", description: "Island coconut and warm sands.", image_url: "/assets/mist_placeholder.png" },

  // Group B: Bath & Body Works
  { name: "Into the Night", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Floral", top_notes: "Dark Berries", heart_notes: "Midnight Jasmine", base_notes: "Rich Amber", vibe_tag: "Alluring", intensity: "Strong", occasion: "Evening", description: "A timeless, feminine, alluring blend.", image_url: "/assets/mist_placeholder.png" },
  { name: "In the Stars", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Woody", top_notes: "Starflower", heart_notes: "Sandalwood Musk", base_notes: "Sugared Tangelo", vibe_tag: "Radiant", intensity: "Medium", occasion: "Daily", description: "Make every moment glow.", image_url: "/assets/mist_placeholder.png" },
  { name: "You're the One", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Floral", top_notes: "White Birch", heart_notes: "Velvety Rose", base_notes: "A Drop of Strawberry Nectar", vibe_tag: "Confident", intensity: "Strong", occasion: "Special", description: "A luxurious blend of soft rose.", image_url: "/assets/mist_placeholder.png" },
  { name: "Forever Red", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Fruity", top_notes: "Fiery Pomegranate", heart_notes: "Red Peony", base_notes: "Vanilla Rum", vibe_tag: "Passionate", intensity: "Strong", occasion: "Date Night", description: "A passionate blend of pomegranate & red peony.", image_url: "/assets/mist_placeholder.png" },
  { name: "A Thousand Wishes", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Floral", top_notes: "Pink Prosecco", heart_notes: "Crystal Peonies", base_notes: "Amaretto Crème", vibe_tag: "Festive", intensity: "Medium", occasion: "Celebration", description: "Warm your heart a thousand times over.", image_url: "/assets/mist_placeholder.png" },
  { name: "Champagne Toast", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Fruity", top_notes: "Bubbly Champagne", heart_notes: "Sparkling Berries", base_notes: "Juicy Tangerine", vibe_tag: "Celebratory", intensity: "Medium", occasion: "Party", description: "A cheers-worthy spritzer.", image_url: "/assets/mist_placeholder.png" },
  { name: "Pure Wonder", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Floral", top_notes: "Iced Rosé", heart_notes: "Star Jasmine", base_notes: "Warm White Amber", vibe_tag: "Dreamy", intensity: "Light", occasion: "Daily", description: "Delight in a sense of wonder.", image_url: "/assets/mist_placeholder.png" },
  { name: "Gingham", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Fresh", top_notes: "Blue Freesia", heart_notes: "White Peach", base_notes: "Fresh Clementine", vibe_tag: "Vibrant", intensity: "Medium", occasion: "Spring", description: "Fresh. Vibrant. Happy.", image_url: "/assets/mist_placeholder.png" },
  { name: "Warm Vanilla Sugar", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Oriental", top_notes: "Intoxicating Vanilla", heart_notes: "White Orchid", base_notes: "Sparkling Sugar", vibe_tag: "Cozy", intensity: "Medium", occasion: "Daily", description: "A cozy, enveloping, irresistible blend.", image_url: "/assets/mist_placeholder.png" },
  { name: "Viva Vanilla", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Oriental", top_notes: "Rich Vanilla", heart_notes: "Spun Sugar", base_notes: "Amber", vibe_tag: "Sweet", intensity: "Medium", occasion: "Daily", description: "Long live vanilla.", image_url: "/assets/mist_placeholder.png" },
  { name: "Pink Obsessed", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Fruity", top_notes: "Blushing Jasmine", heart_notes: "Praline", base_notes: "Vanilla Woods", vibe_tag: "Playful", intensity: "Medium", occasion: "Daily", description: "A sweet, addictive obsession.", image_url: "/assets/mist_placeholder.png" },
  { name: "Midnight Addiction", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Oriental", top_notes: "Dark Cherry", heart_notes: "Black Raspberry", base_notes: "Velvet Musk", vibe_tag: "Sensual", intensity: "Strong", occasion: "Night", description: "Irresistible midnight allure.", image_url: "/assets/mist_placeholder.png" },
  { name: "Japanese Cherry Blossom", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Floral", top_notes: "Cherry Blossom", heart_notes: "Asian Pear", base_notes: "Sandalwood", vibe_tag: "Classic", intensity: "Medium", occasion: "Daily", description: "An iconic, graceful floral.", image_url: "/assets/mist_placeholder.png" },
  { name: "Dark Kiss", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Oriental", top_notes: "Black Raspberry", heart_notes: "Burgundy Rose", base_notes: "Dark Vanilla Bean", vibe_tag: "Seductive", intensity: "Strong", occasion: "Evening", description: "A seductive blend of dark berries.", image_url: "/assets/mist_placeholder.png" },
  { name: "Dream Bright", brand: "Bath & Body Works", category: "Body Mists & Care", price: 3000, scent_family: "Fruity", top_notes: "Sapphire Berries", heart_notes: "Night-Blooming Orchid", base_notes: "Crystalized Vanilla", vibe_tag: "Radiant", intensity: "Medium", occasion: "Daily", description: "A brilliant, unforgettable dream.", image_url: "/assets/mist_placeholder.png" },

  // Group C: Designer Perfumes
  { name: "Chanel No. 5", brand: "Chanel", category: "Luxury Perfumes", price: 25000, scent_family: "Floral", top_notes: "Aldehydes", heart_notes: "Jasmine", base_notes: "Sandalwood", vibe_tag: "Classic", intensity: "Strong", occasion: "Formal", description: "The essence of femininity.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Sauvage", brand: "Dior", category: "Luxury Perfumes", price: 22000, scent_family: "Fresh", top_notes: "Bergamot", heart_notes: "Pepper", base_notes: "Ambroxan", vibe_tag: "Bold", intensity: "Strong", occasion: "Daily", description: "A radically fresh composition.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Black Orchid", brand: "Tom Ford", category: "Luxury Perfumes", price: 28000, scent_family: "Oriental", top_notes: "Truffle", heart_notes: "Black Orchid", base_notes: "Patchouli", vibe_tag: "Luxurious", intensity: "Strong", occasion: "Evening", description: "A luxurious and sensual fragrance.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Bloom", brand: "Gucci", category: "Luxury Perfumes", price: 21000, scent_family: "Floral", top_notes: "Rangoon Creeper", heart_notes: "Jasmine Bud", base_notes: "Tuberose", vibe_tag: "Feminine", intensity: "Medium", occasion: "Spring", description: "Capturing the spirit of the contemporary.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Libre", brand: "YSL", category: "Luxury Perfumes", price: 23000, scent_family: "Floral", top_notes: "Lavender", heart_notes: "Orange Blossom", base_notes: "Musk", vibe_tag: "Free", intensity: "Strong", occasion: "Daily", description: "The fragrance of freedom.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Eros", brand: "Versace", category: "Luxury Perfumes", price: 18000, scent_family: "Fresh", top_notes: "Mint", heart_notes: "Green Apple", base_notes: "Tonka Bean", vibe_tag: "Passionate", intensity: "Strong", occasion: "Evening", description: "Love, passion, beauty, and desire.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Si", brand: "Armani", category: "Luxury Perfumes", price: 20000, scent_family: "Chypre", top_notes: "Cassis", heart_notes: "May Rose", base_notes: "Vanilla", vibe_tag: "Elegant", intensity: "Medium", occasion: "Daily", description: "Chic, sultry, intense and soft.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Candy", brand: "Prada", category: "Luxury Perfumes", price: 19000, scent_family: "Oriental", top_notes: "Caramel", heart_notes: "Powdery Notes", base_notes: "Vanilla", vibe_tag: "Sweet", intensity: "Medium", occasion: "Daily", description: "A playful and sophisticated scent.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Her", brand: "Burberry", category: "Luxury Perfumes", price: 20000, scent_family: "Fruity", top_notes: "Strawberry", heart_notes: "Jasmine", base_notes: "Musk", vibe_tag: "Youthful", intensity: "Medium", occasion: "Daily", description: "An embodiment of the Londoner attitude.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Light Blue", brand: "Dolce & Gabbana", category: "Luxury Perfumes", price: 17000, scent_family: "Fresh", top_notes: "Sicilian Lemon", heart_notes: "Bamboo", base_notes: "Cedar", vibe_tag: "Breezy", intensity: "Light", occasion: "Summer", description: "The joy of living the light blue Mediterranean life.", image_url: "/assets/perfume_placeholder.png" },
  { name: "L'Interdit", brand: "Givenchy", category: "Luxury Perfumes", price: 22000, scent_family: "Floral", top_notes: "Orange Blossom", heart_notes: "Tuberose", base_notes: "Vetiver", vibe_tag: "Daring", intensity: "Strong", occasion: "Evening", description: "A tribute to bold femininity.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Omnia Crystalline", brand: "Bvlgari", category: "Luxury Perfumes", price: 18000, scent_family: "Floral", top_notes: "Bamboo", heart_notes: "Lotus", base_notes: "Balsa Wood", vibe_tag: "Pure", intensity: "Light", occasion: "Daily", description: "Capturing the glowing clarity of crystal light.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Terre d'Hermès", brand: "Hermès", category: "Luxury Perfumes", price: 24000, scent_family: "Woody", top_notes: "Orange", heart_notes: "Pepper", base_notes: "Vetiver", vibe_tag: "Earthy", intensity: "Medium", occasion: "Daily", description: "Feeling the earth, lying on the ground.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Donna Born In Roma", brand: "Valentino", category: "Luxury Perfumes", price: 23000, scent_family: "Floral", top_notes: "Blackcurrant", heart_notes: "Jasmine", base_notes: "Bourbon Vanilla", vibe_tag: "Edgy", intensity: "Medium", occasion: "Evening", description: "A modern haute couture floriental.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Euphoria", brand: "Calvin Klein", category: "Luxury Perfumes", price: 16000, scent_family: "Oriental", top_notes: "Pomegranate", heart_notes: "Lotus", base_notes: "Mahogany", vibe_tag: "Mysterious", intensity: "Strong", occasion: "Evening", description: "Experience the mystery of euphoria.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Le Male", brand: "Jean Paul Gaultier", category: "Luxury Perfumes", price: 18000, scent_family: "Oriental", top_notes: "Mint", heart_notes: "Lavender", base_notes: "Vanilla", vibe_tag: "Iconic", intensity: "Strong", occasion: "Daily", description: "As virile as it is sexy.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Jazz Club", brand: "Maison Margiela (Replica)", category: "Luxury Perfumes", price: 21000, scent_family: "Woody", top_notes: "Pink Pepper", heart_notes: "Rum Absolute", base_notes: "Tobacco Leaf", vibe_tag: "Cozy", intensity: "Medium", occasion: "Evening", description: "Head-y cocktails and cigars.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Chloé Eau de Parfum", brand: "Chloé", category: "Luxury Perfumes", price: 19000, scent_family: "Floral", top_notes: "Peony", heart_notes: "Rose", base_notes: "Cedarwood", vibe_tag: "Romantic", intensity: "Medium", occasion: "Daily", description: "A fresh and feminine fragrance.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Daisy", brand: "Marc Jacobs", category: "Luxury Perfumes", price: 17000, scent_family: "Floral", top_notes: "Wild Berries", heart_notes: "White Violet", base_notes: "Sandalwood", vibe_tag: "Playful", intensity: "Light", occasion: "Spring", description: "Charmingly simple with a signature quality.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Explorer", brand: "Mont Blanc", category: "Luxury Perfumes", price: 18000, scent_family: "Woody", top_notes: "Bergamot", heart_notes: "Vetiver", base_notes: "Patchouli", vibe_tag: "Adventurous", intensity: "Medium", occasion: "Daily", description: "An unconventional woody-aromatic-leather.", image_url: "/assets/perfume_placeholder.png" },
  { name: "La Vie Est Belle", brand: "Lancome", category: "Luxury Perfumes", price: 21000, scent_family: "Floral", top_notes: "Blackcurrant", heart_notes: "Iris", base_notes: "Praline", vibe_tag: "Joyful", intensity: "Strong", occasion: "Daily", description: "A universal declaration to the beauty of life.", image_url: "/assets/perfume_placeholder.png" },
  { name: "Green Tea", brand: "Elizabeth Arden", category: "Luxury Perfumes", price: 8000, scent_family: "Fresh", top_notes: "Lemon", heart_notes: "Green Tea", base_notes: "Oakmoss", vibe_tag: "Refreshing", intensity: "Light", occasion: "Daily", description: "Energizes the body, excites the senses.", image_url: "/assets/perfume_placeholder.png" }
];

module.exports = seedProducts;
